apiVersion: v1
kind: Service
metadata:
  name: invana-engine-{{ .Release.Name }}-chart-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: invana-engine-{{ .Release.Name }}-chart-svc
spec:
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
   
  selector:
    app: invana-engine-{{ .Release.Name }}-dep

status:
  loadBalancer: {}