apiVersion: v1
kind: Service
metadata:
  name: janus-{{ .Release.Name }}-chart-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: janus-{{ .Release.Name }}-chart-svc
spec:
  ports:
    - name: "http"
      port: 8182
      targetPort: 8182
   
  selector:
    app: janus-{{ .Release.Name }}-dep

status:
  loadBalancer: {}